// lib/core/utils/localization_helper.dart

class LocalizationHelper {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // General / Home
      'app_name': 'Dukandar',
      'sub_title': 'Premium Business Calculator',
      'favorites': 'Favorites',
      'no_favorites': 'Pin frequent products here for 1-tap access',
      'quick_access': 'Quick Access',
      'home': 'Home',
      'history': 'History',
      'settings': 'Settings',
      'shop_profile': 'Shop Profile',
      
      // Calculator Card Titles
      'price_to_weight': 'Price → Weight',
      'price_to_weight_sub': 'Type budget, get exact weight',
      'weight_to_price': 'Weight → Price',
      'weight_to_price_sub': 'Type weight, get exact price',
      'profit_calc': 'Profit Calculator',
      'profit_calc_sub': 'Calculate margin and profits',
      'discount_calc': 'Discount Calculator',
      'discount_calc_sub': 'Apply percentage discounts',
      'gst_calc': 'GST Calculator',
      'gst_calc_sub': 'Add or remove GST instantly',
      'prod_lib': 'Product Library',
      'prod_lib_sub': 'Save frequent item prices',
      
      // Screen labels & inputs
      'product_name': 'Product Name',
      'product_name_hint': 'e.g., Rice, Sugar, Oil',
      'product_price': 'Product Price',
      'base_quantity': 'Base Qty',
      'customer_amount': 'Customer Amount',
      'customer_weight': 'Customer Weight',
      'cost_price': 'Cost Price (₹)',
      'selling_price': 'Selling Price (₹)',
      'original_price': 'Original Price (₹)',
      'discount_percentage': 'Discount Percentage',
      'amount': 'Amount (₹)',
      'gst_percentage': 'GST Percentage',
      'add_gst': 'Add GST (+)',
      'remove_gst': 'Remove GST (Inclusive)',
      
      // Results
      'result_receive': 'Customer should receive',
      'result_pay': 'Customer should pay',
      'profit': 'Profit',
      'loss': 'Loss',
      'profit_margin': 'Profit/Loss Margin',
      'margin_percent': 'Margin %',
      'savings': 'You Save',
      'final_price': 'Final Price',
      'base_amount': 'Base Amount (excl. GST)',
      'gst_value': 'GST Value',
      'total_amount': 'Total Amount (incl. GST)',
      'rounded': 'rounded',
      'formula_breakdown': 'Formula Breakdown',

      // Product Library & dialogs
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'name': 'Name',
      'category': 'Category',
      'price': 'Price',
      'unit': 'Unit',
      'is_favorite': 'Favorite',
      'search_products': 'Search products...',
      'no_products': 'No products yet. Add your first product to save time!',
      'delete_confirm': 'Are you sure you want to delete this product?',
      'product_saved': 'Product saved successfully!',
      'product_deleted': 'Product deleted!',
      
      // History
      'no_history': 'No calculations yet. Start calculating to build history!',
      'clear_all': 'Clear All',
      'clear_history_confirm': 'Are you sure you want to clear all history logs?',
      'history_cleared': 'History cleared!',
      'search_history': 'Search history...',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_week': 'This Week',
      'older': 'Older',
      're_calculate': 'Re-calculate',

      // Shop Profile
      'shop_details': 'Shop Details',
      'owner_name': 'Owner Name',
      'default_currency': 'Default Currency',
      'default_weight_unit': 'Default Weight Unit',
      'select_avatar': 'Select Shop Avatar',
      'profile_saved': 'Profile updated successfully!',
      
      // Settings
      'appearance': 'Appearance',
      'theme_mode': 'Theme Mode',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'theme_system': 'System Theme',
      'language': 'Language',
      'history_settings': 'History Settings',
      'auto_save': 'Auto-save history',
      'about': 'About',
      'app_version': 'App Version',
      'reset_app': 'Reset Application',
      'reset_confirm': 'This will delete ALL data. Are you sure you want to proceed?',
      'app_reset_success': 'Application has been reset successfully!',
      'share_app': 'Share App',
      'rate_app': 'Rate App',
      'copy_clipboard': 'Copied to clipboard!',
    },
    'hi': {
      // General / Home
      'app_name': 'दुकानदार',
      'sub_title': 'प्रीमियम बिजनेस कैलकुलेटर',
      'favorites': 'पसंदीदा सामान',
      'no_favorites': 'जल्दी उपयोग के लिए अपने रोज के सामान को यहाँ पिन करें',
      'quick_access': 'त्वरित पहुंच',
      'home': 'होम',
      'history': 'इतिहास',
      'settings': 'सेटिंग्स',
      'shop_profile': 'दुकान की प्रोफाइल',
      
      // Calculator Card Titles
      'price_to_weight': 'दाम → वजन',
      'price_to_weight_sub': 'बजट दर्ज करें, सही वजन पाएं',
      'weight_to_price': 'वजन → दाम',
      'weight_to_price_sub': 'वजन दर्ज करें, सही दाम पाएं',
      'profit_calc': 'मुनाफा कैलकुलेटर',
      'profit_calc_sub': 'मार्जिन और मुनाफा निकालें',
      'discount_calc': 'छूट कैलकुलेटर',
      'discount_calc_sub': 'प्रतिशत छूट लागू करें',
      'gst_calc': 'GST कैलकुलेटर',
      'gst_calc_sub': 'तुरंत GST जोड़ें या हटाएं',
      'prod_lib': 'सामान की सूची',
      'prod_lib_sub': 'रोज के सामान के दाम सेव करें',
      
      // Screen labels & inputs
      'product_name': 'सामान का नाम',
      'product_name_hint': 'जैसे: चावल, चीनी, तेल',
      'product_price': 'सामान का दाम',
      'base_quantity': 'मूल मात्रा',
      'customer_amount': 'ग्राहक का बजट',
      'customer_weight': 'ग्राहक का वजन',
      'cost_price': 'खरीद मूल्य (₹)',
      'selling_price': 'बिक्री मूल्य (₹)',
      'original_price': 'मूल दाम (₹)',
      'discount_percentage': 'छूट प्रतिशत',
      'amount': 'राशि (₹)',
      'gst_percentage': 'GST प्रतिशत',
      'add_gst': 'GST जोड़ें (+)',
      'remove_gst': 'GST हटाएं (शामिल)',
      
      // Results
      'result_receive': 'ग्राहक को वजन दें',
      'result_pay': 'ग्राहक से दाम लें',
      'profit': 'मुनाफा',
      'loss': 'नुकसान',
      'profit_margin': 'लाभ/हानि मार्जिन',
      'margin_percent': 'मार्जिन %',
      'savings': 'आपकी बचत',
      'final_price': 'अंतिम दाम',
      'base_amount': 'मूल राशि (बिना GST)',
      'gst_value': 'GST राशि',
      'total_amount': 'कुल राशि (GST के साथ)',
      'rounded': 'लगभग',
      'formula_breakdown': 'कैलकुलेशन का विवरण',

      // Product Library & dialogs
      'add_product': 'सामान जोड़ें',
      'edit_product': 'बदलाव करें',
      'save': 'सेव करें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'name': 'नाम',
      'category': 'श्रेणी',
      'price': 'दाम',
      'unit': 'इकाई (Unit)',
      'is_favorite': 'पसंदीदा',
      'search_products': 'सामान खोजें...',
      'no_products': 'कोई सामान नहीं है। पहला सामान जोड़ें!',
      'delete_confirm': 'क्या आप वाकई इस सामान को सूची से हटाना चाहते हैं?',
      'product_saved': 'सामान सेव हो गया!',
      'product_deleted': 'सामान हटा दिया गया!',
      
      // History
      'no_history': 'अभी तक कोई हिसाब नहीं है। इतिहास देखने के लिए हिसाब शुरू करें!',
      'clear_all': 'सभी मिटाएं',
      'clear_history_confirm': 'क्या आप वाकई सभी इतिहास मिटाना चाहते हैं?',
      'history_cleared': 'इतिहास मिटा दिया गया!',
      'search_history': 'इतिहास खोजें...',
      'today': 'आज',
      'yesterday': 'कल',
      'this_week': 'इस हफ्ते',
      'older': 'पुराना',
      're_calculate': 'दोबारा हिसाब',

      // Shop Profile
      'shop_details': 'दुकान की जानकारी',
      'owner_name': 'मालिक का नाम',
      'default_currency': 'डिफ़ॉल्ट मुद्रा (Currency)',
      'default_weight_unit': 'डिफ़ॉल्ट वजन की इकाई',
      'select_avatar': 'दुकान का अवतार चुनें',
      'profile_saved': 'प्रोफाइल सेव हो गई!',
      
      // Settings
      'appearance': 'दिखावट (Appearance)',
      'theme_mode': 'थीम मोड',
      'theme_light': 'लाइट मोड',
      'theme_dark': 'डार्क मोड',
      'theme_system': 'सिस्टम थीम',
      'language': 'भाषा (Language)',
      'history_settings': 'इतिहास सेटिंग्स',
      'auto_save': 'हिसाब अपने आप सेव करें',
      'about': 'ऐप के बारे में',
      'app_version': 'ऐप वर्जन',
      'reset_app': 'ऐप रीसेट करें',
      'reset_confirm': 'इससे सारा डाटा डिलीट हो जाएगा। क्या आप जारी रखना चाहते हैं?',
      'app_reset_success': 'ऐप सफलतापूर्वक रीसेट हो गया है!',
      'share_app': 'ऐप शेयर करें',
      'rate_app': 'ऐप को रेट करें',
      'copy_clipboard': 'क्लिपबोर्ड पर कॉपी हो गया!',
    }
  };

  /// Translate a key based on selected language
  static String translate(String key, String language) {
    final Map<String, String> langDict = _translations[language] ?? _translations['en']!;
    return langDict[key] ?? key;
  }
}
